version: '3.8'

networks:
  nestjs_k6:
    name: "nestjs_k6"

services:
  app_local:
    container_name: app_local
    working_dir: /app
    command: sh -c "npm run start:debug"
    build:
      context: .
      args:
        BUILD_STAGE: development
    ports:
      - '${PORT:-3000}:3000'
      - '${DEBUG_PORT:-9229}:9229'
    volumes:
      - .:/app

  app_prod:
    container_name: app_prod
    build:
      context: .
      args:
        BUILD_STAGE: production
    ports:
      - '${PORT:-3000}:3000'
    networks:
      - nestjs_k6
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
